# Generated by Django 4.0.5 on 2022-07-23 07:36

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='academy/<django.db.models.fields.CharField>/logo')),
            ],
        ),
        migrations.CreateModel(
            name='AcademyLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('academy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.academy')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('hiphop', 'hiphop'), ('b-boying', 'b-boying'), ('popping', 'popping'), ('locking', 'locking'), ('k-pop', 'k-pop'), ('waacking', 'waacking'), ('house', 'house'), ('krump', 'krump'), ("girl's hiphop", "girl's hiphop"), ('default', 'default')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('video', models.FileField(upload_to='genre/<django.db.models.fields.CharField>/video')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('started_at', models.DateField()),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('academy', models.ManyToManyField(related_name='academies', to='user.academy')),
                ('major', models.ManyToManyField(related_name='majors', to='user.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('started_at', models.DateField()),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courses_count', models.SmallIntegerField(default=0)),
                ('tier', models.CharField(choices=[('GM', 'Grand-Master'), ('M', 'Master'), ('P', 'Pletinum'), ('G', 'Gold'), ('S', 'Silver'), ('B', 'Bronze'), ('U', 'Unranked')], default='Unranked', max_length=2)),
                ('genre', models.ManyToManyField(related_name='genres', to='user.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademyLocationImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='academy/<django.db.models.fields.CharField>/location')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user.academylocation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=12)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=32)),
                ('birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='<django.db.models.fields.EmailField>/profile_image')),
                ('mentee', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.mentee')),
                ('mentor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.mentor')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
    ]
