# Generated by Django 4.0.5 on 2022-07-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_mentee_tier_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
