# Generated by Django 4.0.5 on 2022-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_mentor_major_mentor_genre_alter_mentee_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='video',
            field=models.FileField(null=True, upload_to='genre/<django.db.models.fields.CharField>/video'),
        ),
    ]
