# Generated by Django 4.0.5 on 2022-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_genre_description_alter_genre_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='academylocation',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academylocation',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='academylocation',
            name='detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='academylocation',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='academylocationimage',
            name='image',
            field=models.ImageField(null=True, upload_to='academy/<django.db.models.fields.CharField>/location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='<django.db.models.fields.EmailField>/profile_image'),
        ),
    ]
