# Generated by Django 4.0.5 on 2022-07-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_academy_description_alter_academylocation_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academy',
            name='logo',
            field=models.ImageField(null=True, upload_to='academy/<django.db.models.fields.CharField>/logo'),
        ),
    ]
