# Generated by Django 4.0.5 on 2022-07-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_academy_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academylocation',
            name='academy',
        ),
        migrations.AddField(
            model_name='academy',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='academy',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.academylocation'),
        ),
        migrations.AddField(
            model_name='academy',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='academy',
            field=models.ManyToManyField(related_name='mentors', to='user.academy'),
        ),
    ]
