# Generated by Django 4.0.5 on 2022-07-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
        ('user', '0010_alter_user_options_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academylocationimage',
            name='location',
        ),
        migrations.AlterField(
            model_name='academy',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='util.location'),
        ),
        migrations.DeleteModel(
            name='AcademyLocation',
        ),
        migrations.DeleteModel(
            name='AcademyLocationImage',
        ),
    ]
