# Generated by Django 4.0.5 on 2022-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('academy', 'academy'), ('lesson', 'lesson')], default='academy', max_length=20),
            preserve_default=False,
        ),
    ]
