# Generated by Django 4.0.5 on 2022-07-29 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0011_remove_academylocationimage_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('price', models.IntegerField(default=0)),
                ('recruit_number', models.SmallIntegerField(default=0)),
                ('academy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.academy')),
                ('genre', models.ManyToManyField(related_name='lessons', to='user.genre')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='util.location')),
                ('mentor', models.ManyToManyField(related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
