# Generated by Django 4.0.5 on 2022-08-08 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0002_lesson_description_lesson_title_alter_lesson_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='mentee',
            field=models.ManyToManyField(related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
