# Generated by Django 4.0.5 on 2022-08-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_academylocationimage_location_and_more'),
        ('lesson', '0003_lesson_mentee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='genre',
        ),
        migrations.AddField(
            model_name='lesson',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.genre'),
            preserve_default=False,
        ),
    ]
