# Generated by Django 4.0.5 on 2022-08-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_academylocationimage_location_and_more'),
        ('lesson', '0004_alter_lesson_options_remove_lesson_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.genre'),
        ),
    ]
